In [4]:
import numpy as np

In [15]:
mat_A = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(mat_A)
det_A = 1*(0*9 - 8*6) - 2*(4*9 - 7*6) + 3*(4*8 - 7*0)
deter_A = np.linalg.det(mat_A)
print(f'Определитель матрицы: {det_A}, {deter_A}')
inv_A = np.linalg.inv(mat_A)
print(f'Матрица обратная с помощью numpy:\n{inv_A}')

[[1 2 3]
 [4 0 6]
 [7 8 9]]
Определитель матрицы: 60, 59.999999999999986
Матрица обратная с помощью numpy:
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [6]:
minor_A=mat_A[:]
minor_A[0,0] = (0*9)-(8*6)
minor_A[0,1] = (4*9)-(7*6)
minor_A[0,2] = (4*8)-(7*0)
minor_A[1,0] = (2*9)-(8*3)
minor_A[1,1] = (1*9)-(7*3)
minor_A[1,2] = (1*8)-(7*2)
minor_A[2,0] = (2*6)-(0*3)
minor_A[2,1] = (1*6)-(4*3)
minor_A[2,2] = (1*0)-(4*2)
print(f'Матрица миноров:\n{minor_A}')

Матрица миноров:
[[-48  -6  32]
 [ -6 -12  -6]
 [ 12  -6  -8]]


In [7]:
mat_alg_dop = minor_A[:]
mat_alg_dop[0,1] = - mat_alg_dop[0,1]
mat_alg_dop[1,0], mat_alg_dop[1,2] = - mat_alg_dop[1,0], - mat_alg_dop[1,2]
mat_alg_dop[2,1] = - mat_alg_dop[2,1]
print(f'Матрица алгебраических дополнений:\n{mat_alg_dop}')

Матрица алгебраических дополнений:
[[-48   6  32]
 [  6 -12   6]
 [ 12   6  -8]]


In [8]:
trans_mat = mat_alg_dop.transpose()
print(f'Транспонированная матрица алгебраических дополнений:\n{trans_mat}')

Транспонированная матрица алгебраических дополнений:
[[-48   6  12]
 [  6 -12   6]
 [ 32   6  -8]]


In [13]:
res_matrix = trans_mat / det_A
print(f'Обратная матрица:\n{res_matrix}')

Обратная матрица:
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [4]:
matrix = np.array([[0,0,0,0],[0,0,1,0],[0,0,0,0],[0,0,0,0]])
print(f'Матрица размером 4 на 4 с рангом 1:\n{matrix}')  

Матрица размером 4 на 4 с рангом 1:
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
rang = np.linalg.matrix_rank(matrix,0)
print(rang)

1
