In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 1])
Q, R = np.linalg.qr(A)

print('A=\n',A)
print('Q=\n',Q)
print('R=\n',R)
X0=0

A=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Q=
 [[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R=
 [[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [10]:
# print(np.dot(Q, R))

In [14]:
R1 = R[:2, :2]
B1 = np.dot(np.transpose(Q), B)[:2]
X1 = np.linalg.solve(R1,B1)
print(f'X1:{X1}')
X = np.append(X1,X0)
print(f'X: {X}')
norm_X = np.linalg.norm(X)
print(f'Норма одного из бесконечных решений: {norm_X}')

X1:[-3.5         3.33333333]
X: [-3.5         3.33333333  0.        ]
Норма одного из бесконечных решений: 4.833333333333305


In [13]:
norma = np.linalg.norm(np.dot(A, X) - B)
print(f'Псевдорешение с минимальной нормой: {norma}')

Псевдорешение с минимальной нормой: 2.857738033247041


In [15]:
X = np.array([-3, 2.5, 0.5])
np.linalg.norm(X),  np.linalg.norm(np.dot(A, X) - B) 

(3.9370039370059056, 3.278719262151)