In [20]:
import numpy as np

In [21]:
# mat_A = np.array([[1,2,3],[4,5,6],[7,8,9,],[10,11,12]],int)
# print(mat_A)

In [22]:
# print(mat_A.shape) # количество строк и столбцов-->размерность матрицы

In [23]:
# mat_C = mat_A * 2
# print(mat_C)

In [24]:
# mat_Sum = mat_A + mat_C
# print(mat_Sum)

In [19]:
vec_A = np.array([[1,2,3,4,5]])
vec_B = np.array([[6,7,8,9,-1]])
vec_C = vec_B.transpose()
print(vec_A)
print(" ")
print(f'Транспонированная матрица:\n{vec_C}')
print(f'Произведение типа А*C: \n{vec_A * vec_C}')

[[1 2 3 4 5]]
 
Транспонированная матрица:
[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [-1]]
Произведение типа А*C: 
[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [-1 -2 -3 -4 -5]]


In [26]:
#Условие (5Е) - 1, где E - единичная матрица
mat_E = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]])
print(f'Единичная матрциа 5х5:\n{mat_E}')

Единичная матрциа 5х5:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [27]:
mat_Mut = 5*mat_E
print(mat_Mut)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [29]:
mat_Res = mat_Mut - 1
print(f'Матрица соответсвующая условию "5E - 1": \n{mat_Res}')

Матрица соответсвующая условию "5E - 1": 
[[ 4 -1 -1 -1 -1]
 [-1  4 -1 -1 -1]
 [-1 -1  4 -1 -1]
 [-1 -1 -1  4 -1]
 [-1 -1 -1 -1  4]]
