In [1]:
import numpy as np

In [2]:
mat_A = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(mat_A)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [4]:
det_A = 1*(0*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 0*7)
deter_A = np.linalg.det(mat_A)
print(f'Определитель матрицы равен: {det_A}\nОпределитель матрицы через numpy:{deter_A}')

Определитель матрицы равен: 60
Определитель матрица через numpy:59.999999999999986
