In [1]:
import numpy as np

In [13]:
matr_a = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(f'Матрица переменнх А:\n{matr_a}')
vec_ans = np.array([12,2,1])
print(f'Вектор коеффициентов С:\n{vec_ans}')
mat_roots = np.linalg.solve(matr_a,vec_ans)
print(f'Корни уравнений: {round(mat_roots[0],2)},{round(mat_roots[1],2)},{round(mat_roots[2],2)}')


Матрица переменнх А:
[[1 2 3]
 [4 0 6]
 [7 8 9]]
Вектор коеффициентов С:
[12  2  1]
Корни уравнений: -9.2,0.9,6.47


In [16]:
print(f'Матрица переменнх А:\n{matr_a}')
vec_ans = np.array([12,2,1])
print(f'Вектор коеффициентов С:\n{vec_ans}')
inv_a = np.linalg.inv(matr_a)
det_a = np.linalg.det(matr_a)
res = np.dot(inv_a,vec_ans)
print(f'det =', det_a)
print(f'Корни уравнений:\n{res}')

Матрица переменнх А:
[[1 2 3]
 [4 0 6]
 [7 8 9]]
Вектор коеффициентов С:
[12  2  1]
det = 59.999999999999986
Корни уравнений:
[-9.2         0.9         6.46666667]
