In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

In [2]:
A = np.array([[1,2,3],[2,6,21],[4,28,73]])
P, L, U = scipy.linalg.lu(A)
print('P=\n', P)
print('L=\n', L)
print('U=\n',U)

P=
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L=
 [[1.    0.    0.   ]
 [0.5   1.    0.   ]
 [0.25  0.625 1.   ]]
U=
 [[  4.      28.      73.    ]
 [  0.      -8.     -15.5   ]
 [  0.       0.      -5.5625]]


In [5]:
B = np.array([3,1,7])
C = L * U
res = np.linalg.solve(C, B)
print(f'Корни решения уравнений: {res}')

Корни решения уравнений: [ 0.75       -0.125      -1.25842697]
