In [2]:
import numpy as np

In [29]:
mat_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'Матрица переменнх А:\n{mat_a}')
# mat_b = np.array([[2,5,1]])
mat_b = np.array([[0,0,0]]) # ответ если вектор B[0,0,0] у системы есть решения
print(f'Вектор коеффициентов B:\n{mat_b}')
det_a = np.linalg.det(mat_a)
print(f'det =', round(det_a,2))
rang1 = np.linalg.matrix_rank(mat_a)
print(f'Ранг матрицы: {rang1}')
C = np.concatenate((mat_a,mat_b.T), axis=1)
print(C)
rang2 = np.linalg.matrix_rank(C)
print(f'Ранг расширенной матрицы: {rang2}')
if not rang1==rang2:
    print('Система уравнений является несовместной')
else:
    print('У системы уравнений есть бесконечное множество решений')

Матрица переменнх А:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Вектор коеффициентов B:
[[0 0 0]]
det = -0.0
Ранг матрицы: 2
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
Ранг расширенной матрицы: 2
У системы уравнений есть бесконечное множетсво решений
